// module5-chat-dashboard/frontend/src/pages/ChatPage.jsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { chatApi } from '../api/client'

/* ---- helpers ---- */
function formatTime(iso) {
  if (!iso) return ''
  // Backend stores UTC without Z, frontend temp msgs have Z; normalize
  const d = new Date(iso.endsWith('Z') ? iso : iso + 'Z')
  if (isNaN(d.getTime())) return ''
  const now = new Date()
  const isToday = d.toDateString() === now.toDateString()
  const pad = (n) => String(n).padStart(2, '0')
  const time = `${pad(d.getHours())}:${pad(d.getMinutes())}`
  return isToday ? time : `${d.getMonth() + 1}/${d.getDate()} ${time}`
}

function truncate(str, max = 30) {
  if (!str) return ''
  return str.length > max ? str.slice(0, max) + '…' : str
}

/* ================================================================
   ChatPage — 智能客服主页面
   ================================================================ */
export default function ChatPage() {
  /* state */
  const [sessions, setSessions] = useState([])
  const [activeId, setActiveId] = useState(null)
  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')
  const [sending, setSending] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [loadingSessions, setLoadingSessions] = useState(true)

  const messagesEnd = useRef(null)
  const fileInput = useRef(null)
  const inputRef = useRef(null)

  /* scroll to bottom */
  const scrollBottom = useCallback(() => {
    messagesEnd.current?.scrollIntoView({ behavior: 'smooth' })
  }, [])

  useEffect(() => { scrollBottom() }, [messages, scrollBottom])

  /* load sessions */
  const loadSessions = useCallback(async () => {
    try {
      setLoadingSessions(true)
      const res = await chatApi.listSessions()
      setSessions(res.data)
      return res.data
    } catch (e) {
      console.error('加载会话列表失败', e)
      return []
    } finally {
      setLoadingSessions(false)
    }
  }, [])

  useEffect(() => { loadSessions() }, [loadSessions])

  /* auto-select first session */
  useEffect(() => {
    if (!activeId && sessions.length > 0) {
      setActiveId(sessions[0].id)
    }
  }, [sessions, activeId])

  /* load messages when session changes */
  useEffect(() => {
    if (!activeId) return
    let cancelled = false
    chatApi.getMessages(activeId).then(res => {
      if (!cancelled) setMessages(res.data)
    }).catch(console.error)
    return () => { cancelled = true }
  }, [activeId])

  /* create session */
  const createSession = async () => {
    try {
      const res = await chatApi.createSession('新会话')
      setSessions(prev => [res.data, ...prev])
      setActiveId(res.data.id)
      setMessages([])
      inputRef.current?.focus()
    } catch (e) {
      console.error('创建会话失败', e)
    }
  }

  /* switch session */
  const switchSession = (id) => {
    setActiveId(id)
    setMessages([])
  }

  /* upload document */
  const handleUpload = async (e) => {
    const file = e.target.files?.[0]
    if (!file || !activeId) return

    // auto-create session if none
    let targetId = activeId
    if (!targetId) {
      try {
        const res = await chatApi.createSession(file.name.replace(/\.[^.]+$/, ''))
        setSessions(prev => [res.data, ...prev])
        targetId = res.data.id
        setActiveId(targetId)
      } catch (err) {
        console.error(err)
        return
      }
    }

    setUploading(true)
    try {
      await chatApi.uploadDoc(targetId, file)
      await loadSessions()
      // reload messages to show any system note
      chatApi.getMessages(targetId).then(res => setMessages(res.data)).catch(() => {})
    } catch (err) {
      alert('文档上传失败: ' + (err.response?.data?.detail || err.message))
    } finally {
      setUploading(false)
      e.target.value = ''
    }
  }

  /* send message */
  const sendMessage = async () => {
    const text = input.trim()
    if (!text || sending) return

    let targetId = activeId
    if (!targetId) {
      try {
        const res = await chatApi.createSession('新会话')
        setSessions(prev => [res.data, ...prev])
        targetId = res.data.id
        setActiveId(targetId)
      } catch (err) {
        console.error(err)
        return
      }
    }

    // optimistically add user message
    const tempUser = {
      id: Date.now(),
      session_id: targetId,
      role: 'user',
      content: text,
      language: 'auto',
      created_at: new Date().toISOString(),
    }
    setMessages(prev => [...prev, tempUser])
    setInput('')
    setSending(true)

    try {
      const res = await chatApi.sendMessage(targetId, text, 'auto')
      // replace temp user + add real assistant
      setMessages(prev => {
        const filtered = prev.filter(m => m.id !== tempUser.id)
        return [...filtered, res.data.user_message, res.data.assistant_message]
      })
      // refresh session list (title may have changed)
      loadSessions()
    } catch (err) {
      setMessages(prev => {
        const filtered = prev.filter(m => m.id !== tempUser.id)
        return [...filtered, {
          ...tempUser,
          id: tempUser.id,
          content: text,
        }, {
          id: Date.now() + 1,
          session_id: targetId,
          role: 'assistant',
          content: '⚠️ 回复生成失败，请稍后重试。',
          language: 'auto',
          created_at: new Date().toISOString(),
        }]
      })
    } finally {
      setSending(false)
    }
  }

  /* feedback */
  const handleFeedback = async (msgId, type) => {
    try {
      await chatApi.feedback(msgId, type)
      setMessages(prev => prev.map(m =>
        m.id === msgId ? { ...m, feedback: type } : m
      ))
    } catch (e) {
      console.error('反馈提交失败', e)
    }
  }

  /* keyboard */
  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  /* ---- render ---- */
  const activeSession = sessions.find(s => s.id === activeId)

  return (
    <div className="chat-layout">
      {/* ---- sidebar ---- */}
      <aside className="chat-sidebar">
        <div className="sidebar-header">
          <h3>会话列表</h3>
          <button className="btn-new-session" onClick={createSession}>
            ＋ 新建会话
          </button>
        </div>

        <div className="session-list">
          {loadingSessions ? (
            <div className="loading-center" style={{ height: 80 }}>
              <span className="spinner" />
            </div>
          ) : sessions.length === 0 ? (
            <div style={{ padding: 20, textAlign: 'center', color: 'var(--gray-400)', fontSize: 13 }}>
              暂无会话，点击上方按钮创建
            </div>
          ) : (
            sessions.map(s => (
              <div
                key={s.id}
                className={`session-item${s.id === activeId ? ' active' : ''}`}
                onClick={() => switchSession(s.id)}
              >
                <div className="session-title">{s.title}</div>
                <div className="session-meta">
                  {s.doc_name ? `📎 ${s.doc_name}` : formatTime(s.created_at)}
                </div>
              </div>
            ))
          )}
        </div>
      </aside>

      {/* ---- main chat ---- */}
      <section className="chat-main">
        {/* header */}
        <div className="chat-header">
          <h2>{activeSession ? activeSession.title : '智能客服'}</h2>
          <div className="chat-header-actions">
            {activeSession?.doc_name && (
              <span className="doc-badge">📄 {activeSession.doc_name}</span>
            )}
          </div>
        </div>

        {/* messages */}
        <div className="messages-area">
          {messages.length === 0 ? (
            <div className="empty-chat">
              <div className="icon">💬</div>
              <p>上传商品文档或直接提问，AI 客服将为您解答</p>
              <p style={{ fontSize: 12, color: 'var(--gray-300)' }}>
                支持 PDF / Word / TXT / Markdown
              </p>
            </div>
          ) : (
            messages.map((msg, i) => (
              <MessageBubble
                key={msg.id}
                msg={msg}
                onFeedback={(type) => handleFeedback(msg.id, type)}
              />
            ))
          )}

          {/* typing indicator */}
          {sending && (
            <div className="message-row assistant">
              <div className="msg-avatar">🤖</div>
              <div className="msg-bubble typing-bubble">
                <div className="typing-indicator">
                  <span /><span /><span />
                </div>
              </div>
            </div>
          )}

          <div ref={messagesEnd} />
        </div>

        {/* input */}
        <div className="chat-input-area">
          <div className="input-row">
            {/* hidden file input */}
            <input
              ref={fileInput}
              type="file"
              accept=".pdf,.doc,.docx,.txt,.md,.markdown"
              style={{ display: 'none' }}
              onChange={handleUpload}
            />
            <button
              className="btn-attach"
              onClick={() => fileInput.current?.click()}
              disabled={uploading}
              title="上传文档"
            >
              {uploading ? <span className="spinner" /> : '+'}
            </button>
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="输入商品相关问题，Enter 发送，Shift+Enter 换行"
              rows={1}
              disabled={sending}
            />
            <button
              className="btn-send"
              onClick={sendMessage}
              disabled={!input.trim() || sending}
              title="发送"
            >➤</button>
          </div>
        </div>
      </section>
    </div>
  )
}

/* ================================================================
   MessageBubble — 单条消息组件
   ================================================================ */
function MessageBubble({ msg, onFeedback }) {
  const isUser = msg.role === 'user'

  return (
    <div className={`message-row ${msg.role}`}>
      <div className="msg-avatar">{isUser ? '👤' : '🤖'}</div>
      <div>
        <div className="msg-bubble">{msg.content}</div>
        <div className="msg-footer">
          <span className="msg-time">{formatTime(msg.created_at)}</span>

          {!isUser && (
            <>
              <button
                className={`btn-feedback${msg.feedback === 'like' ? ' active-like' : ''}`}
                onClick={() => onFeedback('like')}
                title="有帮助"
              >👍</button>
              <button
                className={`btn-feedback${msg.feedback === 'dislike' ? ' active-dislike' : ''}`}
                onClick={() => onFeedback('dislike')}
                title="没帮助"
              >👎</button>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

// module5-chat/frontend/views/chat/ChatPage.vue
<template>
  <div class="chat-page sketch-shell">
    <el-row :gutter="16" style="height:100%">
      <el-col :span="6">
        <el-card shadow="never" class="session-panel">
          <template #header>
            <span>会话列表</span>
            <el-button size="small" type="primary" style="float:right" @click="newSession">新建</el-button>
          </template>
          <div class="session-list">
            <div
              v-for="s in sessions"
              :key="s.id"
              class="session-item"
              :class="{ active: s.id === currentSessionId }"
              @click="switchSession(s.id)"
            >
              <strong>{{ s.title || '新会话' }}</strong>
              <span class="session-doc" v-if="s.doc_name">📄 {{ s.doc_name }}</span>
              <el-button size="small" text type="danger" class="del-btn" @click.stop="deleteSession(s.id)">×</el-button>
            </div>
            <el-empty v-if="sessions.length === 0" description="还没有会话，点右上角新建" />
          </div>
        </el-card>
      </el-col>

      <el-col :span="18">
        <el-card shadow="never" class="chat-panel">
          <template #header>
            <div class="chat-head">
              <span>{{ currentTitle || '新对话' }}</span>
              <div class="chat-tools">
                <el-radio-group v-model="replyLang" size="small">
                  <el-radio-button label="auto">自动</el-radio-button>
                  <el-radio-button label="zh">中文</el-radio-button>
                  <el-radio-button label="en">EN</el-radio-button>
                </el-radio-group>
                <el-upload
                  :auto-upload="false"
                  :show-file-list="false"
                  :on-change="onUploadDoc"
                  accept=".pdf,.doc,.docx,.txt,.md"
                >
                  <el-button size="small" :loading="uploading">
                    <el-icon><Upload /></el-icon> 上传文档
                  </el-button>
                </el-upload>
              </div>
            </div>
          </template>

          <div class="message-area" ref="msgArea">
            <div v-for="m in messages" :key="m.id" class="msg-row" :class="m.role">
              <div class="msg-bubble">
                <div class="msg-text">{{ m.content }}</div>
                <div class="msg-meta">
                  <span v-if="m.role === 'assistant'">
                    <el-button size="small" text :type="m.feedback === 'like' ? 'primary' : ''" @click="feedback(m.id, 'like')">👍</el-button>
                    <el-button size="small" text :type="m.feedback === 'dislike' ? 'danger' : ''" @click="feedback(m.id, 'dislike')">👎</el-button>
                  </span>
                  <span class="msg-time">{{ formatTime(m.created_at) }}</span>
                </div>
              </div>
            </div>
            <div v-if="loading" class="msg-row assistant">
              <div class="msg-bubble typing">正在思考...</div>
            </div>
          </div>

          <div class="input-area">
            <el-input
              v-model="inputText"
              placeholder="问产品、售后、政策… 支持中英"
              size="large"
              @keyup.enter="sendMsg"
              :disabled="loading"
            >
              <template #append>
                <el-button :loading="loading" @click="sendMsg" type="primary">发送</el-button>
              </template>
            </el-input>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup>
import { ref, computed, nextTick, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import request from '@/api/request'

const sessions = ref([])
const messages = ref([])
const currentSessionId = ref(null)
const inputText = ref('')
const loading = ref(false)
const uploading = ref(false)
const replyLang = ref('auto')
const msgArea = ref(null)

const currentTitle = computed(() => {
  const s = sessions.value.find((x) => x.id === currentSessionId.value)
  return s ? (s.doc_name || s.title || '新会话') : ''
})

function formatTime(iso) {
  if (!iso) return ''
  const d = new Date(String(iso).endsWith('Z') ? iso : `${iso}Z`)
  if (Number.isNaN(d.getTime())) return String(iso).slice(11, 19)
  const pad = (n) => String(n).padStart(2, '0')
  return `${pad(d.getHours())}:${pad(d.getMinutes())}`
}

function scrollBottom() {
  nextTick(() => {
    if (msgArea.value) msgArea.value.scrollTop = msgArea.value.scrollHeight
  })
}

async function loadSessions() {
  try {
    sessions.value = await request.get('/chat/sessions')
    if (!currentSessionId.value && sessions.value.length) {
      switchSession(sessions.value[0].id)
    }
  } catch {}
}

async function newSession() {
  try {
    const data = await request.post('/chat/sessions', { title: '新会话' })
    sessions.value.unshift(data)
    switchSession(data.id)
  } catch {}
}

function switchSession(id) {
  currentSessionId.value = id
  loadMessages()
}

async function loadMessages() {
  if (!currentSessionId.value) return
  try {
    messages.value = await request.get(`/chat/messages/${currentSessionId.value}`)
    scrollBottom()
  } catch {}
}

async function sendMsg() {
  if (!inputText.value.trim() || loading.value) return
  loading.value = true
  const text = inputText.value.trim()
  try {
    if (!currentSessionId.value) {
      const created = await request.post('/chat/sessions', { title: text.slice(0, 20) || '新会话' })
      sessions.value.unshift(created)
      currentSessionId.value = created.id
    }
    const data = await request.post('/chat/message', {
      session_id: currentSessionId.value,
      content: text,
      language: replyLang.value,
    })
    if (data?.user_message && data?.assistant_message) {
      messages.value.push(data.user_message, data.assistant_message)
    } else if (data?.content) {
      messages.value.push(
        { id: `u-${Date.now()}`, role: 'user', content: text, created_at: new Date().toISOString() },
        data,
      )
    }
    inputText.value = ''
    scrollBottom()
  } catch {} finally {
    loading.value = false
  }
}

async function onUploadDoc(uploadFile) {
  uploading.value = true
  try {
    if (!currentSessionId.value) {
      const created = await request.post('/chat/sessions', {
        title: uploadFile.name?.slice(0, 40) || '文档会话',
      })
      sessions.value.unshift(created)
      currentSessionId.value = created.id
    }
    const fd = new FormData()
    fd.append('session_id', String(currentSessionId.value))
    fd.append('file', uploadFile.raw)
    await request.post('/chat/upload', fd, {
      headers: { 'Content-Type': 'multipart/form-data' },
    })
    ElMessage.success('文档上传成功，索引已建立')
    loadSessions()
  } catch {} finally {
    uploading.value = false
  }
}

async function feedback(msgId, type) {
  try {
    await request.post('/chat/feedback', { message_id: msgId, feedback_type: type })
    messages.value = messages.value.map((m) => (m.id === msgId ? { ...m, feedback: type } : m))
  } catch {}
}

async function deleteSession(id) {
  try {
    await ElMessageBox.confirm('确定删除此会话？', '提示', { type: 'warning' })
    await request.delete(`/chat/sessions/${id}`)
    if (currentSessionId.value === id) {
      currentSessionId.value = null
      messages.value = []
    }
    loadSessions()
  } catch {}
}

onMounted(loadSessions)
</script>

<style scoped>
.chat-page { height: calc(100vh - 140px); }
.session-panel, .chat-panel { height: 100%; }
.session-list { max-height: calc(100vh - 260px); overflow-y: auto; }
.session-item {
  padding: 10px 12px;
  border-bottom: 1.5px dashed rgba(44, 58, 66, 0.15);
  cursor: pointer;
  display: flex;
  flex-direction: column;
  position: relative;
  border-radius: 12px;
  margin-bottom: 4px;
}
.session-item:hover { background: rgba(47, 111, 106, 0.08); }
.session-item.active {
  background: rgba(47, 111, 106, 0.14);
  border-left: 3px solid var(--accent);
}
.session-doc { font-size: 12px; color: var(--ink-soft); }
.del-btn { position: absolute; right: 4px; top: 4px; }
.chat-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}
.chat-tools { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
.message-area {
  flex: 1;
  overflow-y: auto;
  padding: 12px;
  min-height: 300px;
  max-height: calc(100vh - 360px);
}
.msg-row { display: flex; margin-bottom: 12px; }
.msg-row.user { justify-content: flex-end; }
.msg-bubble {
  max-width: 72%;
  padding: 10px 14px;
  border: 1.5px solid var(--line);
  border-radius: 18px 14px 16px 20px / 16px 18px 14px 18px;
  white-space: pre-wrap;
  word-break: break-word;
  background: #fff;
}
.msg-row.user .msg-bubble {
  background: rgba(47, 111, 106, 0.9);
  color: #fff;
  border-color: #1f4f4b;
}
.msg-bubble.typing { color: #888; font-style: italic; }
.msg-meta { display: flex; align-items: center; gap: 4px; margin-top: 4px; font-size: 12px; }
.msg-time { color: #999; margin-left: auto; }
.msg-row.user .msg-time { color: rgba(255,255,255,0.75); }
.input-area { margin-top: 12px; }
</style>
